---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: from-cli-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay:latest
        command:
          - bash
          - -c
        args:
          - "echo hello"
