apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-s3-
spec:
  entrypoint: input-artifact
  templates:
    - name: input-artifact
      inputs:
        artifacts:
          - name: my-art
            path: my-artifact
            s3:
              bucket: my-bucket
              endpoint: minio:9000
              insecure: true
              key: output/hello_world.txt
              accessKeySecret:
                name: my-minio-cred
                key: accesskey
              secretKeySecret:
                name: my-minio-cred
                key: secretkey
      container:
        image: debian:latest
        command: [sh, -c]
        args: ["cat my-artifact"]
